# version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynet

  server:
    build: ./server
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SECURITY_JWT_ENCRYPTION_SECRET: ${JWT_ENCRYPTION_SECRET}

      SPRING_MAIL_USERNAME: ${SMTP_USERNAME}
      SPRING_MAIL_PASSWORD: ${SMTP_PASSWORD}

      CORS_ALLOWED_ORIGINS: ${REACT_APP_URL}

      API_BASE_URL: ${SPRING_APP_URL}

    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - mynet

  client:
    build: ./client
    container_name: react-app
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - mynet

volumes:
  mysql_data:

networks:
  mynet:
