spring:
  application:
    name: michelin-kitchen

  datasource:
    url: ${MYSQL_DB_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    rest:
      base-path: /api
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      orm:
        jdbc:
          bind: TRACE

security:
  jwt:
    encryption_secret: ${JWT_ENCRYPTION_SECRET}

cors:
  allowed-origins: ${REACT_APP_URL}
