spring:
  application:
    name: michelin-kitchen

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    rest:
      base-path: /api

security:
  jwt:
    encryption_secret: ${JWT_ENCRYPTION_SECRET}
