spring:
  application:
    name: michelin-kitchen

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    rest:
      base-path: /api
  mail:
    host: smtp.gmail.com
    port: 587
    username: minhtengi1412@gmail.com
    password: czlanxfljywmzcby
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    encryption_secret: ${JWT_ENCRYPTION_SECRET}
