spring:
  application:
    name: michelin-kitchen

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update

  data:
    rest:
      base-path: /api
